USE EXAM;


-- Вариант №1


-- Задание №1
SELECT DISTINCT
	PRODUCTS.MFR_ID,
	PRODUCTS.PRODUCT_ID,
	OFFICES.REGION
FROM
	ORDERS
	INNER JOIN PRODUCTS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT
	INNER JOIN SALESREPS ON SALESREPS.EMPL_NUM = ORDERS.REP
	INNER JOIN OFFICES ON OFFICES.OFFICE = SALESREPS.REP_OFFICE
WHERE
	OFFICES.REGION = 'Eastern'
;


-- Задание №2
SELECT
	ORDERS.REP,
	SALESREPS.NAME,
	AVG(PRODUCTS.PRICE) AS 'Avg Price'
FROM
	SALESREPS
	INNER JOIN ORDERS ON ORDERS.REP = SALESREPS.EMPL_NUM
	INNER JOIN PRODUCTS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT
GROUP BY ORDERS.REP, SALESREPS.NAME
HAVING AVG(PRODUCTS.PRICE) > 600
;
