USE UNIVER;
GO


-- Задание №1
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
GO


-- Задание №2
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
	AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';
GO


-- Задание №3
SELECT 
	FACULTY.FACULTY_NAME AS 'Факультет',
	PULPIT.PULPIT_NAME AS 'Кафедра',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	SUBJECT.SUBJECT_NAME AS 'Дисциплина',
	STUDENT.NAME AS 'Имя Студента',
	CASE
		WHEN (PROGRESS.NOTE = 6) THEN 'шесть'
		WHEN (PROGRESS.NOTE = 7) THEN 'семь'
		WHEN (PROGRESS.NOTE = 8) THEN 'восемь'
		ELSE CAST(PROGRESS.NOTE AS varchar(10))
	END 'Оценка'
FROM 
	PROGRESS 
	INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN SUBJECT ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
	INNER JOIN PULPIT ON PULPIT.PULPIT = SUBJECT.PULPIT
WHERE 
	PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY
	PROGRESS.NOTE DESC
;
GO


-- Задание №4
SELECT
	PULPIT.PULPIT_NAME AS 'Кафедра',
	isnull(TEACHER.TEACHER_NAME, '***') AS 'Преподаватель'
FROM
	PULPIT LEFT OUTER JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT
;
GO


-- Задание №6
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
GO