use UNIVER;
GO


-- Задание №1
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	FACULTY.FACULTY = 'ИТ'
GROUP BY ROLLUP (
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
)
;


-- Задание №2
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	FACULTY.FACULTY = 'ИТ'
GROUP BY CUBE (
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
)
;


-- Задание №3
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-40 01 02' -- ИСиТ
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
UNION ALL
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-47 01 01' -- ИД
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
;


-- Задание №4
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-40 01 02' -- ИСиТ
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
INTERSECT
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-47 01 01' -- ИД
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
;


-- Задание №5
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-40 01 02' -- ИСиТ
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
EXCEPT
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROFESSION.PROFESSION = '1-47 01 01' -- ИД
GROUP BY
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
;


-- Задание №7
SELECT
	FACULTY.FACULTY_NAME AS 'Факультет',
	GROUPS.IDGROUP AS 'Группа',
	COUNT(*) AS 'Количество студентов'
FROM
	STUDENT
	INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
GROUP BY ROLLUP (
	FACULTY.FACULTY_NAME,
	GROUPS.IDGROUP
)
;

SELECT
	AUDITORIUM_TYPE.AUDITORIUM_TYPENAME AS 'Тип аудитории',
	COUNT(*) AS 'Количество аудиторий',
	SUM(AUDITORIUM.AUDITORIUM_CAPACITY) AS 'Суммарная вместительность'
FROM
	AUDITORIUM
	INNER JOIN AUDITORIUM_TYPE ON AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
GROUP BY ROLLUP (
	AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
)
;
