USE UNIVER;
GO


-- Задание №1
SELECT 
	FACULTY.FACULTY_NAME AS 'Факультет',
	PULPIT.PULPIT_NAME AS 'Кафедра',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROFESSION.QUALIFICATION AS 'Квалификация'
FROM
	FACULTY,
	PULPIT,
	PROFESSION
WHERE
	FACULTY.FACULTY = PULPIT.FACULTY
	AND FACULTY.FACULTY = PROFESSION.FACULTY
	AND FACULTY.FACULTY_NAME IN (
		SELECT FACULTY_NAME 
		FROM FACULTY
		WHERE
			FACULTY_NAME LIKE '%технология%'
			OR FACULTY_NAME LIKE '%технологии%'
	)
;


-- Задание №2
SELECT 
	FACULTY.FACULTY_NAME AS 'Факультет',
	PULPIT.PULPIT_NAME AS 'Кафедра',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROFESSION.QUALIFICATION AS 'Квалификация'
FROM
	FACULTY 
	INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE
	FACULTY.FACULTY_NAME IN (
		SELECT FACULTY_NAME 
		FROM FACULTY
		WHERE
			FACULTY_NAME LIKE '%технология%'
			OR FACULTY_NAME LIKE '%технологии%'
	)
;


-- Задание №3
SELECT 
	FACULTY.FACULTY_NAME AS 'Факультет',
	PULPIT.PULPIT_NAME AS 'Кафедра',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROFESSION.QUALIFICATION AS 'Квалификация'
FROM
	FACULTY 
	INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE
	FACULTY.FACULTY_NAME LIKE '%технология%'
	OR FACULTY.FACULTY_NAME LIKE '%технологии%'
;


-- Задание №4
SELECT
	AUDITORIUM_TYPE AS 'Тип',
	AUDITORIUM_NAME AS 'Аудитория',
	AUDITORIUM_CAPACITY AS 'Вместимость'
FROM 
	AUDITORIUM AS top_auditorium
WHERE 
	AUDITORIUM_NAME = (
		SELECT TOP(1) AUDITORIUM_NAME
		FROM AUDITORIUM AS bottom_auditorium
		WHERE bottom_auditorium.AUDITORIUM_TYPE = top_auditorium.AUDITORIUM_TYPE
		ORDER BY AUDITORIUM_CAPACITY DESC
	)
ORDER BY AUDITORIUM_CAPACITY DESC
;


-- Задание №5
SELECT f.FACULTY_NAME 
FROM FACULTY AS f
WHERE NOT EXISTS (
	SELECT *
	FROM PULPIT AS p
	WHERE f.FACULTY = p.FACULTY
)
;


-- Задание №6
SELECT top(1)
	(
		SELECT AVG(PROGRESS.NOTE)
		FROM PROGRESS
		WHERE PROGRESS.SUBJECT LIKE 'ОАиП'
	) AS 'ОАиП',
	(
		SELECT AVG(PROGRESS.NOTE)
		FROM PROGRESS
		WHERE PROGRESS.SUBJECT LIKE 'БД'
	) AS 'БД',
	(
		SELECT AVG(PROGRESS.NOTE)
		FROM PROGRESS
		WHERE PROGRESS.SUBJECT LIKE 'СУБД'
	) AS 'СУБД'
;	


-- Задание №7
SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM_CAPACITY >= ALL(
	SELECT AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM_TYPE LIKE 'ЛК%'
)
;


-- Задание №8
SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM_CAPACITY >= ANY(
	SELECT AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM_TYPE LIKE 'ЛК%'
)
;


-- Задание №10
SELECT 
	BDAY AS 'День рождения',
	STRING_AGG(NAME, ', ') AS 'Студенты'
FROM STUDENT
GROUP BY BDAY
HAVING COUNT(*) > 1
ORDER BY BDAY
;
