USE UNIVER;
GO

-- Задание №6
SELECT
	CASE
		WHEN PROGRESS.NOTE < 4 THEN 'Плохо'
		WHEN PROGRESS.NOTE BETWEEN 4 AND 5 THEN 'Удовлетворительно'
		WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN 'Нормально'
		WHEN PROGRESS.NOTE BETWEEN 8 AND 10 THEN 'Отлично'
		ELSE CAST(PROGRESS.NOTE AS varchar(3))
	END AS 'Оценка',
	COUNT(*) AS 'Количество'
FROM 
	PROGRESS
	INNER JOIN STUDENT ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
WHERE
	FACULTY.FACULTY = 'ИТ'
GROUP BY
	CASE
		WHEN PROGRESS.NOTE < 4 THEN 'Плохо'
		WHEN PROGRESS.NOTE BETWEEN 4 AND 5 THEN 'Удовлетворительно'
		WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN 'Нормально'
		WHEN PROGRESS.NOTE BETWEEN 8 AND 10 THEN 'Отлично'
		ELSE CAST(PROGRESS.NOTE AS varchar(3))
	END
ORDER BY 'Количество' ASC
;
