USE UNIVER;
GO


-- Задание №1
SELECT
	t.AUDITORIUM_TYPENAME AS 'Тип аудитории',
	MAX(a1.AUDITORIUM_CAPACITY) AS 'Максимальная вместительность',
	MIN(a1.AUDITORIUM_CAPACITY) AS 'Минимальная вместительность',
	AVG(a1.AUDITORIUM_CAPACITY) AS 'Средняя вместительность',
	SUM(a1.AUDITORIUM_CAPACITY) AS 'Суммарная вместительность',
	COUNT(*) AS 'Количество аудиторий'
FROM
	AUDITORIUM AS a1
	INNER JOIN AUDITORIUM_TYPE AS t ON a1.AUDITORIUM_TYPE = t.AUDITORIUM_TYPE
GROUP BY
	t.AUDITORIUM_TYPENAME
;


-- Задание №3
SELECT *
FROM (
	SELECT
		CASE
			WHEN NOTE < 4 THEN 'До 4'
			WHEN NOTE BETWEEN 4 AND 6 THEN 'От 4 до 6'
			WHEN NOTE BETWEEN 7 AND 8 THEN 'От 7 до 8'
			WHEN NOTE BETWEEN 9 AND 10 THEN 'От 9 до 10'
			ELSE '???'
		END AS 'Диапазон оценок',
		COUNT(*) AS 'Количество оценок',
		STRING_AGG(NOTE, ', ') AS 'Оценки'
	FROM PROGRESS
	GROUP BY 
		CASE
			WHEN NOTE < 4 THEN 'До 4'
			WHEN NOTE BETWEEN 4 AND 6 THEN 'От 4 до 6'
			WHEN NOTE BETWEEN 7 AND 8 THEN 'От 7 до 8'
			WHEN NOTE BETWEEN 9 AND 10 THEN 'От 9 до 10'
			ELSE '???'
		END
) AS T
ORDER BY
	CASE T.[Диапазон оценок]
		WHEN 'До 4' THEN 4
		WHEN 'От 4 до 6' THEN 3
		WHEN 'От 7 до 8' THEN 2
		WHEN 'От 9 до 10' THEN 1
		ELSE 0
	END
;


-- Задание №4
SELECT
	GROUPS.YEAR_FIRST AS 'Год',
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM 
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY
	GROUPS.YEAR_FIRST,
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
ORDER BY 'Средняя оценка' DESC
;


-- Задание №5
SELECT
	GROUPS.YEAR_FIRST AS 'Год',
	FACULTY.FACULTY_NAME AS 'Факультет',
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM 
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	PROGRESS.SUBJECT IN ('СУБД', 'ОАиП')
GROUP BY
	GROUPS.YEAR_FIRST,
	FACULTY.FACULTY_NAME,
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
ORDER BY 'Средняя оценка' DESC
;


-- Задание №6
SELECT 
	PROFESSION.PROFESSION_NAME AS 'Специальность',
	PROGRESS.SUBJECT AS 'Предмет',
	ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))), 2) AS 'Средняя оценка'
FROM
	FACULTY
	INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE
	FACULTY.FACULTY = 'ИТ'
GROUP BY
	PROFESSION.PROFESSION_NAME,
	PROGRESS.SUBJECT
ORDER BY 'Средняя оценка' DESC
;


-- Задание №7
SELECT 
	PROGRESS.NOTE AS 'Оценка',
	COUNT(*) AS 'Количество студентов'
FROM 
	PROGRESS
WHERE
	PROGRESS.NOTE IN (9, 8)
GROUP BY 
	PROGRESS.NOTE
HAVING 
	COUNT(*) > 0
ORDER BY PROGRESS.NOTE DESC
;
